// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (
    id, 
    shop_id, 
    status, 
    parent_id, 
    name, 
    slug, 
    created_by,
    created_at
) 
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateCategoryParams struct {
	ID        pgtype.UUID
	ShopID    pgtype.UUID
	Status    string
	ParentID  pgtype.UUID
	Name      string
	Slug      string
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.Exec(ctx, createCategory,
		arg.ID,
		arg.ShopID,
		arg.Status,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories 
WHERE id = $1 AND shop_id = $2
`

type DeleteCategoryParams struct {
	ID     pgtype.UUID
	ShopID pgtype.UUID
}

func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.ShopID)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, shop_id, status, parent_id, name, slug, created_by, updated_by, created_at, updated_at FROM categories 
WHERE id = $1 AND shop_id = $2
`

type GetCategoryByIDParams struct {
	ID     pgtype.UUID
	ShopID pgtype.UUID
}

func (q *Queries) GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, arg.ID, arg.ShopID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Status,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, shop_id, status, parent_id, name, slug, created_by, updated_by, created_at, updated_at FROM categories 
WHERE shop_id = $1 AND slug = $2
`

type GetCategoryBySlugParams struct {
	ShopID pgtype.UUID
	Slug   string
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.ShopID, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Status,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryChildren = `-- name: GetCategoryChildren :many
SELECT id, shop_id, status, parent_id, name, slug, created_by, updated_by, created_at, updated_at FROM categories
WHERE shop_id = $1 AND parent_id = $2
ORDER BY name ASC
`

type GetCategoryChildrenParams struct {
	ShopID   pgtype.UUID
	ParentID pgtype.UUID
}

func (q *Queries) GetCategoryChildren(ctx context.Context, arg GetCategoryChildrenParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoryChildren, arg.ShopID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Status,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET 
    name = $1,
    slug = $2,
    status = $3,
    parent_id = $4,
    updated_by = $5,
    updated_at = NOW()
WHERE id = $6 AND shop_id = $7
RETURNING id, shop_id, status, parent_id, name, slug, created_by, updated_by, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name      string
	Slug      string
	Status    string
	ParentID  pgtype.UUID
	UpdatedBy pgtype.UUID
	ID        pgtype.UUID
	ShopID    pgtype.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.ParentID,
		arg.UpdatedBy,
		arg.ID,
		arg.ShopID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Status,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
