// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category_products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBySlug = `-- name: CountBySlug :one
SELECT
    1
FROM categories 
WHERE slug = $1::text
`

func (q *Queries) CountBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, countBySlug, slug)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listCategoriesByProductID = `-- name: ListCategoriesByProductID :many
SELECT c.id, c.shop_id, c.status, c.parent_id, c.name, c.slug, c.created_by, c.updated_by, c.created_at, c.updated_at
FROM categories c
JOIN category_products cp ON c.id = cp.category_id
WHERE cp.shop_id = $1 AND cp.product_id = $2
`

type ListCategoriesByProductIDParams struct {
	ShopID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) ListCategoriesByProductID(ctx context.Context, arg ListCategoriesByProductIDParams) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByProductID, arg.ShopID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Status,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProductFromAllCategories = `-- name: RemoveProductFromAllCategories :exec
DELETE FROM category_products
WHERE shop_id = $1::uuid 
    AND product_id = $2::uuid
`

type RemoveProductFromAllCategoriesParams struct {
	ShopID    pgtype.UUID
	ProductID pgtype.UUID
}

func (q *Queries) RemoveProductFromAllCategories(ctx context.Context, arg RemoveProductFromAllCategoriesParams) error {
	_, err := q.db.Exec(ctx, removeProductFromAllCategories, arg.ShopID, arg.ProductID)
	return err
}

const removeProductFromCategory = `-- name: RemoveProductFromCategory :exec


DELETE FROM category_products
WHERE shop_id = $1::uuid 
    AND category_id = $2::uuid 
    AND product_id = $3::uuid
`

type RemoveProductFromCategoryParams struct {
	ShopID     pgtype.UUID
	CategoryID pgtype.UUID
	ProductID  pgtype.UUID
}

// INSERT INTO category_products (
//
//	shop_id,
//	category_id,
//	product_id
//
// )
// FROM (
//
//	SELECT * FROM ROWS FROM(
//	    unnest(@shop_id::uuid[]),
//	    unnest(@category_id::uuid[]),
//	    unnest(@product_id::uuid[])
//	) AS tmp(shop_id, category_id, product_id)
//
// ) AS u
// ON CONFLICT (shop_id, category_id, product_id) DO NOTHING;
func (q *Queries) RemoveProductFromCategory(ctx context.Context, arg RemoveProductFromCategoryParams) error {
	_, err := q.db.Exec(ctx, removeProductFromCategory, arg.ShopID, arg.CategoryID, arg.ProductID)
	return err
}
