// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttributeValue struct {
	ID                 pgtype.UUID
	ProductAttributeID pgtype.UUID
	Name               string
}

type Category struct {
	ID        pgtype.UUID
	ShopID    pgtype.UUID
	Status    string
	ParentID  pgtype.UUID
	Name      string
	Slug      string
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CategoryProduct struct {
	ShopID     pgtype.UUID
	CategoryID pgtype.UUID
	ProductID  pgtype.UUID
}

type Outbox struct {
	ID             pgtype.UUID
	AggregateID    pgtype.UUID
	AggregateType  string
	EventType      string
	Payload        []byte
	PartitionKey   string
	IdempotencyKey pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Product struct {
	ID          pgtype.UUID
	ShopID      pgtype.UUID
	Name        string
	Slug        string
	Description string
	Brand       string
	ThumbUrl    string
	VideoUrl    string
	PriceMin    int64
	PriceMax    int64
	Status      string
	HasVariant  pgtype.Bool
	CreatedBy   pgtype.UUID
	UpdatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProductAttribute struct {
	ID        pgtype.UUID
	ProductID pgtype.UUID
	Name      string
}

type ProductAttributeValue struct {
	SkuID            pgtype.UUID
	AttributeValueID pgtype.UUID
}

type ProductVariant struct {
	SkuID     pgtype.UUID
	ProductID pgtype.UUID
	ShopID    pgtype.UUID
	SkuCode   string
	Price     int64
	Currency  string
	ImageUrl  string
	Status    string
	IsDefault pgtype.Bool
	CreatedBy pgtype.UUID
	UpdatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
