// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateVariants = `-- name: BatchCreateVariants :exec
INSERT INTO product_variants (
    sku_id,
    product_id, 
    shop_id,
    sku_code,
    price,
    currency,
    image_url,
    status,
    is_default,
    created_by,
    created_at
)
SELECT
    unnest($1::uuid[]),
    $2::uuid,
    $3::uuid,
    unnest($4::text[]),
    unnest($5::int[]),
    unnest($6::text[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::boolean[]),
    unnest($10::uuid[]),
    unnest($11::timestamptz[])
`

type BatchCreateVariantsParams struct {
	SkuIds     []pgtype.UUID
	ProductID  pgtype.UUID
	ShopID     pgtype.UUID
	SkuCodes   []string
	Prices     []int32
	Currencies []string
	ImageUrls  []string
	Status     []string
	IsDefaults []bool
	CreatedBys []pgtype.UUID
	CreatedAts []pgtype.Timestamptz
}

func (q *Queries) BatchCreateVariants(ctx context.Context, arg BatchCreateVariantsParams) error {
	_, err := q.db.Exec(ctx, batchCreateVariants,
		arg.SkuIds,
		arg.ProductID,
		arg.ShopID,
		arg.SkuCodes,
		arg.Prices,
		arg.Currencies,
		arg.ImageUrls,
		arg.Status,
		arg.IsDefaults,
		arg.CreatedBys,
		arg.CreatedAts,
	)
	return err
}

const batchLinkVariantAttributes = `-- name: BatchLinkVariantAttributes :exec
INSERT INTO product_attribute_values (
    sku_id,
    attribute_value_id
)
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type BatchLinkVariantAttributesParams struct {
	SkuIds            []pgtype.UUID
	AttributeValueIds []pgtype.UUID
}

func (q *Queries) BatchLinkVariantAttributes(ctx context.Context, arg BatchLinkVariantAttributesParams) error {
	_, err := q.db.Exec(ctx, batchLinkVariantAttributes, arg.SkuIds, arg.AttributeValueIds)
	return err
}
