// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProductBySlug = `-- name: CountProductBySlug :one
SELECT
    1
FROM products
WHERE slug = $1
`

func (q *Queries) CountProductBySlug(ctx context.Context, slug string) (int32, error) {
	row := q.db.QueryRow(ctx, countProductBySlug, slug)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
    id,
    shop_id,
    name, 
    slug, 
    description, 
    brand, 
    thumb_url, 
    video_url, 
    price_min, 
    price_max, 
    status, 
    has_variant, 
    created_by,
    created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateProductParams struct {
	ID          pgtype.UUID
	ShopID      pgtype.UUID
	Name        string
	Slug        string
	Description string
	Brand       string
	ThumbUrl    string
	VideoUrl    string
	PriceMin    int64
	PriceMax    int64
	Status      string
	HasVariant  pgtype.Bool
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Brand,
		arg.ThumbUrl,
		arg.VideoUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.Status,
		arg.HasVariant,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listProductsByShop = `-- name: ListProductsByShop :many
SELECT id, shop_id, name, slug, description, brand, thumb_url, video_url, price_min, price_max, status, has_variant, created_by, updated_by, created_at, updated_at FROM products
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.ThumbUrl,
			&i.VideoUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.Status,
			&i.HasVariant,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
