// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_attributes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateAttributeValues = `-- name: BatchCreateAttributeValues :exec
INSERT INTO attribute_values (
    id, 
    product_attribute_id, 
    value
) 
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[]),
    unnest($3::text[])
`

type BatchCreateAttributeValuesParams struct {
	Ids                 []pgtype.UUID
	ProductAttributeIds []pgtype.UUID
	Values              []string
}

func (q *Queries) BatchCreateAttributeValues(ctx context.Context, arg BatchCreateAttributeValuesParams) error {
	_, err := q.db.Exec(ctx, batchCreateAttributeValues, arg.Ids, arg.ProductAttributeIds, arg.Values)
	return err
}

const batchCreateAttributes = `-- name: BatchCreateAttributes :exec
INSERT INTO product_attributes (
    id,
    product_id,
    name
)
SELECT
    unnest($1::uuid[]),
    $2::uuid,
    unnest($3::text[])
`

type BatchCreateAttributesParams struct {
	Ids       []pgtype.UUID
	ProductID pgtype.UUID
	Names     []string
}

func (q *Queries) BatchCreateAttributes(ctx context.Context, arg BatchCreateAttributesParams) error {
	_, err := q.db.Exec(ctx, batchCreateAttributes, arg.Ids, arg.ProductID, arg.Names)
	return err
}
