// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_variants.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateVariants = `-- name: BatchCreateVariants :exec
INSERT INTO product_variants (
    sku_id,
    product_id, 
    shop_id,
    sku_code,
    price,
    currency,
    image_url,
    status,
    is_default,
    created_by,
    created_at
)
SELECT
    unnest($1::uuid[]),
    $2::uuid,
    $3::uuid,
    unnest($4::text[]),
    unnest($5::bigint[]),
    unnest($6::text[]),
    unnest($7::text[]),
    unnest($8::text[]),
    unnest($9::boolean[]),
    unnest($10::uuid[]),
    unnest($11::timestamptz[])
`

type BatchCreateVariantsParams struct {
	SkuIds     []pgtype.UUID
	ProductID  pgtype.UUID
	ShopID     pgtype.UUID
	SkuCodes   []string
	Prices     []int64
	Currencies []string
	ImageUrls  []string
	Status     []string
	IsDefaults []bool
	CreatedBys []pgtype.UUID
	CreatedAts []pgtype.Timestamptz
}

func (q *Queries) BatchCreateVariants(ctx context.Context, arg BatchCreateVariantsParams) error {
	_, err := q.db.Exec(ctx, batchCreateVariants,
		arg.SkuIds,
		arg.ProductID,
		arg.ShopID,
		arg.SkuCodes,
		arg.Prices,
		arg.Currencies,
		arg.ImageUrls,
		arg.Status,
		arg.IsDefaults,
		arg.CreatedBys,
		arg.CreatedAts,
	)
	return err
}

const batchLinkVariantAttributes = `-- name: BatchLinkVariantAttributes :exec
INSERT INTO product_attribute_values (
    sku_id,
    attribute_value_id
)
SELECT
    unnest($1::uuid[]),
    unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type BatchLinkVariantAttributesParams struct {
	SkuIds            []pgtype.UUID
	AttributeValueIds []pgtype.UUID
}

func (q *Queries) BatchLinkVariantAttributes(ctx context.Context, arg BatchLinkVariantAttributesParams) error {
	_, err := q.db.Exec(ctx, batchLinkVariantAttributes, arg.SkuIds, arg.AttributeValueIds)
	return err
}

const findPriceSkusByIDs = `-- name: FindPriceSkusByIDs :many
SELECT 
    sku_id, 
    price
FROM product_variants
WHERE sku_id = ANY($1::uuid[])
    AND shop_id = $2::uuid
`

type FindPriceSkusByIDsParams struct {
	SkuIds []pgtype.UUID
	ShopID pgtype.UUID
}

type FindPriceSkusByIDsRow struct {
	SkuID pgtype.UUID
	Price int64
}

func (q *Queries) FindPriceSkusByIDs(ctx context.Context, arg FindPriceSkusByIDsParams) ([]FindPriceSkusByIDsRow, error) {
	rows, err := q.db.Query(ctx, findPriceSkusByIDs, arg.SkuIds, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPriceSkusByIDsRow
	for rows.Next() {
		var i FindPriceSkusByIDsRow
		if err := rows.Scan(&i.SkuID, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantAttributeValuesByProductID = `-- name: ListVariantAttributeValuesByProductID :many
SELECT pav.sku_id, pav.attribute_value_id
FROM product_attribute_values pav
JOIN product_variants pv ON pv.sku_id = pav.sku_id
WHERE pv.product_id = $1::uuid
`

func (q *Queries) ListVariantAttributeValuesByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductAttributeValue, error) {
	rows, err := q.db.Query(ctx, listVariantAttributeValuesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductAttributeValue
	for rows.Next() {
		var i ProductAttributeValue
		if err := rows.Scan(&i.SkuID, &i.AttributeValueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProductID = `-- name: ListVariantsByProductID :many
SELECT sku_id, product_id, shop_id, sku_code, price, currency, image_url, status, is_default, created_by, updated_by, created_at, updated_at
FROM product_variants
WHERE product_id = $1::uuid
`

func (q *Queries) ListVariantsByProductID(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.SkuID,
			&i.ProductID,
			&i.ShopID,
			&i.SkuCode,
			&i.Price,
			&i.Currency,
			&i.ImageUrl,
			&i.Status,
			&i.IsDefault,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
