// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkProductSlugExists = `-- name: CheckProductSlugExists :one
SELECT EXISTS (
    SELECT 1
    FROM products
    WHERE shop_id = $1::uuid
      AND slug = $2::text
)
`

type CheckProductSlugExistsParams struct {
	ShopID pgtype.UUID
	Slug   string
}

func (q *Queries) CheckProductSlugExists(ctx context.Context, arg CheckProductSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProductSlugExists, arg.ShopID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
    id,
    shop_id,
    name, 
    slug, 
    description, 
    brand, 
    thumb_url, 
    video_url, 
    price_min, 
    price_max, 
    status, 
    has_variant, 
    created_by,
    created_at
)
VALUES (
    $1::uuid,
    $2::uuid,
    $3::text,
    $4::text, 
    $5::text, 
    $6::text, 
    $7::text, 
    $8::text, 
    $9::bigint, 
    $10::bigint, 
    $11::text, 
    $12::boolean, 
    $13::uuid, 
    $14::timestamptz
)
`

type CreateProductParams struct {
	ID          pgtype.UUID
	ShopID      pgtype.UUID
	Name        string
	Slug        string
	Description string
	Brand       string
	ThumbUrl    string
	VideoUrl    string
	PriceMin    int64
	PriceMax    int64
	Status      string
	HasVariant  bool
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Brand,
		arg.ThumbUrl,
		arg.VideoUrl,
		arg.PriceMin,
		arg.PriceMax,
		arg.Status,
		arg.HasVariant,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products
WHERE id = $1::uuid
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, shop_id, name, slug, description, brand, thumb_url, video_url, price_min, price_max, status, has_variant, created_by, updated_by, created_at, updated_at
FROM products
WHERE id = $1::uuid
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.ThumbUrl,
		&i.VideoUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.Status,
		&i.HasVariant,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByShopAndSlug = `-- name: GetProductByShopAndSlug :one
SELECT id, shop_id, name, slug, description, brand, thumb_url, video_url, price_min, price_max, status, has_variant, created_by, updated_by, created_at, updated_at
FROM products
WHERE shop_id = $1::uuid
  AND slug = $2::text
LIMIT 1
`

type GetProductByShopAndSlugParams struct {
	ShopID pgtype.UUID
	Slug   string
}

func (q *Queries) GetProductByShopAndSlug(ctx context.Context, arg GetProductByShopAndSlugParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByShopAndSlug, arg.ShopID, arg.Slug)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Brand,
		&i.ThumbUrl,
		&i.VideoUrl,
		&i.PriceMin,
		&i.PriceMax,
		&i.Status,
		&i.HasVariant,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsByShop = `-- name: ListProductsByShop :many
SELECT id, shop_id, name, slug, description, brand, thumb_url, video_url, price_min, price_max, status, has_variant, created_by, updated_by, created_at, updated_at FROM products
WHERE shop_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsByShopParams struct {
	ShopID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListProductsByShop(ctx context.Context, arg ListProductsByShopParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByShop, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Brand,
			&i.ThumbUrl,
			&i.VideoUrl,
			&i.PriceMin,
			&i.PriceMax,
			&i.Status,
			&i.HasVariant,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
